name: Auto-Update Documentation

on:
  issue_comment:
    types: [created]

jobs:
  update-docs:
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '[update-docs]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          
      - name: Update Documentation
        uses: csoceanu/code-to-docs@v1.0.3
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          docs-repo-url: ${{ secrets.DOCS_REPO_URL }}
          github-token: ${{ secrets.GH_TOKEN }}
